name: Getting Movie Information

on:
  issues:
    types: [opened, reopened]
env:
  GITHUB_ISSUE_NUMBER: ${{ github.event.issue.number }}
jobs:
  Getting_Movie_Info:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any dependencies, replace 'requirements.txt' with your actual file name

    - name: Extract movie title
      id: extract_movie_title
      run: |
        ISSUE_BODY=$(cat $GITHUB_EVENT_PATH | jq -r .issue.body)
        MOVIE_TITLE=$(echo "$ISSUE_BODY" | grep -oP '(?<=movie_input: ")[^"]+(?=")')
        echo "MOVIE_TITLE=$MOVIE_TITLE" >> $GITHUB_ENV
      
    - name: Run main.py
      env:
        GIT_API_KEY: ${{secrets.GIT_API_KEY}}
        API_KEY: ${{ secrets.API_KEY }}
        MOVIE_TITLE: ${{ env.MOVIE_TITLE }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
      run: python main.py
